{% set version = "1.0.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-satellite
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/satellite_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/satellite/satellite_{{ version }}.tar.gz
  sha256: 3e4c382f905eb0b2d84f03423af2960854e5cf94905a373c6ba3f41a2b72a1ad

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  script: R CMD INSTALL --build .

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp >=0.10.3
    - r-plyr
    - r-raster
    - r-terra
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp >=0.10.3
    - r-plyr
    - r-raster
    - r-terra

test:
  commands:
    - $R -e "library('satellite')"           # [not win]
    - "\"%R%\" -e \"library('satellite')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=satellite
  license: MIT
  summary: Herein, we provide a broad variety of functions which are useful for handling, manipulating, and visualizing satellite-based remote sensing  data. These operations range from mere data import and layer handling (eg  subsetting), over Raster* typical data wrangling (eg crop, extend), to more  sophisticated (pre-)processing
    tasks typically applied to satellite imagery  (eg atmospheric and topographic correction). This functionality is  complemented by a full access to the satellite layers' metadata at any  stage and the documentation of performed actions in a separate log file.  Currently available sensors include Landsat 4-5 (TM), 7 (ETM+),
    and 8  (OLI/TIRS Combined), and additional compatibility is ensured for the Landsat  Global Land Survey data set. Moreover, support for Terra and Aqua-MODIS as  well as PROBA-V is expected to arrive shortly.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
    - conda-forge/r
