# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangcxx_compilerclangxx
    - CONFIG=osx_c_compilertoolchain_ccxx_compilertoolchain_cxx

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "UpvLDC40EQ8cMRbJuZbgy7rGgadxzgOOM049e1ojSP4FrhhCKMQRdPGwrHl1OXQhuV3gWk2pSc9AHytR/PdupnRHH4WNvYC1uUccx+fSV8i4lodAI3j3s4DmlO3WTRIavp0/URdWqwOSpnycCABkn/ZkLFHr2h5moiXCGC6WROoT2/Q4WgonG3bHtoYARdalgXL0YymM9V1v0v2pTiObQWwBLQzeEOwXlc8k+ILY6oQ3IwgbRfH7iAAd2vVD2kjtK6LyjER6NGMlraOQHv3UT+5oD8ENmSgVSF3+0bCfCpOyVxiJdWQlBuBgEidF9PfjQNyokporxWyKnSAmfNgVDDkXd37hED9a1y3iIYG0XmulU0NvNL+xLyp5lFt5F3UwLOXuCrnRpHUlllblHV03Hcpn2S10pYrcjMwfbkm2iqFG6XGVSEw0h5ZsIDHZH97MvOrtseI0TKTuhEMdHTHu08fjW5RmEzHKRQq4lG0U/YEWTC5Dp4N1otNck37MDrCcb8gq+yUw0mTSPBoyQU2R90k9l+WoHJhbAVFCAuEhel2ghtu7quIA+u1eyaRFR6W+acPXbsN4PoswXRqyv/WShI+kpfPYq9RcMahYR+WgscABd/BdBNMxs/WnZ6rXWm9LeCWRxCrwIHyiElyo/wh1otrGu2QiUjltz6jDx/TxyxA="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
