travis:
  secure:
    BINSTAR_TOKEN: brXb5KpHJxZGiRzOzzieznWhgDZis6i4RCkcmxHiqEwTWSAmX+pv5ba7eGZhfUchUKl3oE9i48DtTnBINRRA29f0AtGUmcsljuw7H/Cjf5UzoUFtXzlExP7IAGF84JrbgDQPFwj9bb4sEV0qNiFU6jlr9D3xzMamxy2xxixHnJ0RhFybXOsKKX99ooJTArmfPfL3YfvgAlvQQrOLDOgKzaQ0J5Cgw1sHX3HyvMbrGHNtebAxmADAQRH7l8boaJur2XR3IzvlNMgu9RvsQ9XyrvwPi/fVQASAbrXxXU4zdB8fTh/nsjKZ6FXDyCsDKbMmD+Gql2kCFvb57f6bOemWIsMQn2prs/GKGeoPxY4jvly2hc5KyVNItrQbRfIcdc0M8FidZoAq9Gqqsxi9df1PrNEQShQmhRx+tBji9Gh7wG9QLQ6Q9OaHfBSftsgaWqxMBkqO4fvpiHCuoO24jkk9iSYlSe1nqaqKglfHOBwY+2oZ0UtF7dLyTTjg0MtrWvuoogT7lsPvJf4IH6H6OXRjmrKfIEugTDGRXJ8jwF44KWCMbGMjN1caIGkVo6VWjDU8GOzUBm7GMXLJ9s0pwCL6jSGvrunzFPtWOfuWp6wnK9k4wV6gGfqfjziYT03mT7s5q8elYZcHLKg9Bf+rWpGxbA+hRonPBvrIQNVqfqXaDso=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
