appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: UpvLDC40EQ8cMRbJuZbgy7rGgadxzgOOM049e1ojSP4FrhhCKMQRdPGwrHl1OXQhuV3gWk2pSc9AHytR/PdupnRHH4WNvYC1uUccx+fSV8i4lodAI3j3s4DmlO3WTRIavp0/URdWqwOSpnycCABkn/ZkLFHr2h5moiXCGC6WROoT2/Q4WgonG3bHtoYARdalgXL0YymM9V1v0v2pTiObQWwBLQzeEOwXlc8k+ILY6oQ3IwgbRfH7iAAd2vVD2kjtK6LyjER6NGMlraOQHv3UT+5oD8ENmSgVSF3+0bCfCpOyVxiJdWQlBuBgEidF9PfjQNyokporxWyKnSAmfNgVDDkXd37hED9a1y3iIYG0XmulU0NvNL+xLyp5lFt5F3UwLOXuCrnRpHUlllblHV03Hcpn2S10pYrcjMwfbkm2iqFG6XGVSEw0h5ZsIDHZH97MvOrtseI0TKTuhEMdHTHu08fjW5RmEzHKRQq4lG0U/YEWTC5Dp4N1otNck37MDrCcb8gq+yUw0mTSPBoyQU2R90k9l+WoHJhbAVFCAuEhel2ghtu7quIA+u1eyaRFR6W+acPXbsN4PoswXRqyv/WShI+kpfPYq9RcMahYR+WgscABd/BdBNMxs/WnZ6rXWm9LeCWRxCrwIHyiElyo/wh1otrGu2QiUjltz6jDx/TxyxA=}
